# Generated by Django 5.2.8 on 2025-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["nome"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Categoria"
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="sku",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="SKU"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(verbose_name="Quantidade em Estoque"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome do Produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço (R$)"
            ),
        ),
        migrations.AlterModelTable(
            name="produto",
            table="produtos_produto",
        ),
    ]
