# Generated by Django 5.2.8 on 2025-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "produtos",
            "0002_alter_produto_options_produto_categoria_produto_peso_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="estoque_min",
            field=models.IntegerField(
                default=10,
                help_text="Quantidade mínima antes de gerar alerta",
                verbose_name="Estoque Mínimo",
            ),
        ),
    ]
