# Generated by Django 5.2.8 on 2025-11-16 12:21
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'nome',
                    models.CharField(
                        max_length=255,
                        verbose_name='Nome Completo'
                    )
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name='E-mail'
                    )
                ),
                (
                    'telefone',
                    models.CharField(
                        max_length=50,
                        verbose_name='Telefone'
                    )
                ),
                (
                    'tipo_documento',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('CPF', 'CPF'),
                            ('CNPJ', 'CNPJ'),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name='Tipo de Documento'
                    )
                ),
                (
                    'numero_documento',
                    models.CharField(
                        max_length=20,
                        verbose_name='Número do Documento'
                    )
                ),
                (
                    'endereco',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Endereço Completo'
                    )
                ),
                (
                    'cidade',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name='Cidade'
                    )
                ),
                (
                    'estado',
                    models.CharField(
                        blank=True,
                        max_length=2,
                        verbose_name='Estado'
                    )
                ),
                (
                    'cep',
                    models.CharField(
                        blank=True,
                        max_length=12,
                        verbose_name='CEP'
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True)
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
