# Generated by Django 5.2.8 on 2025-11-16 12:45
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=12, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=20, verbose_name='Número do Documento'),
        ),
    ]
