# Generated by Django 5.2.8 on 2025-11-16
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    # Migration neutra (não faz nada)
    operations = []
