# Generated by Django 5.2.8 on 2025-11-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_celular_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='clientes_cliente',
        ),
    ]
