# Generated by Django 5.2.8 on 2025-11-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_cep_alter_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='celular',
            field=models.CharField(blank=True, max_length=50, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
