# Generated by Django 5.2.8 on 2025-11-18 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_minima",
                    models.IntegerField(
                        default=10, help_text="Quantidade mínima antes de gerar alerta"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "produto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limite de Estoque",
                "verbose_name_plural": "Limites de Estoque",
                "db_table": "stock_thresholds",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("low_stock", "Estoque Baixo"),
                            ("out_of_stock", "Sem Estoque"),
                            ("critical", "Crítico"),
                        ],
                        default="low_stock",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                ("quantidade_atual", models.IntegerField()),
                ("quantidade_minima", models.IntegerField()),
                ("lida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("lida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "lida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_read",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "notifications",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["lida", "-criado_em"],
                        name="notificatio_lida_e37bb7_idx",
                    ),
                    models.Index(
                        fields=["produto", "-criado_em"],
                        name="notificatio_produto_7dcaa7_idx",
                    ),
                ],
            },
        ),
    ]
