# Generated by Django 5.2.6 on 2025-11-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='parcelas',
            field=models.IntegerField(default=1, help_text='Número de parcelas (1 = à vista)'),
        ),
    ]
