# Generated by Django 5.2.6 on 2025-11-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_pagamento_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
