# Generated by Django 5.2.8 on 2025-11-25 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_frete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número da parcela')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_detalhes', to='vendas.pagamento')),
                ('usuario_baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('pagamento', 'numero')},
            },
        ),
    ]
